FrontEnd/Entities/Candidato.cs
using System;
using System.Collections.Generic;

namespace FrontEnd.Entities
{
    public partial class Candidato
    {
        public Candidato()
        {
            Solicitud = new HashSet<Solicitud>();
        }

        public string NombreCandidato { get; set; } = null!;
        public string ApellidoCandidato { get; set; } = null!;
        public int ExpCandidato { get; set; }
        public string GradoEstudio { get; set; } = null!;
        public int TelefonoCandidato { get; set; }
        public long AreaInteres { get; set; }
        public string CorreoUsuario { get; set; } = null!;

        public virtual Categoria AreaInteresNavigation { get; set; } = null!;
        public virtual Usuario CorreoUsuarioNavigation { get; set; } = null!;
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}

FrontEnd/Models/CandidatoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FrontEnd.Models
{
    public class CandidatoViewModel
    {
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Debe ingresar un nombre válido")]
        public string NombreCandidato { get; set; } = null!;
        [Display(Name = "Apellidos")]
        [Required(ErrorMessage = "Debe ingresar un apellido válido")]
        public string ApellidoCandidato { get; set; } = null!;
        [Display(Name = "Experiencia")]
        public int ExpCandidato { get; set; }
        [Display(Name = "Nivel Académico")]
        [Required(ErrorMessage = "Es obligatorio ingresar el nivel académico")]
        public string GradoEstudio { get; set; } = null!;
        [Display(Name = "Teléfono")]
        public int TelefonoCandidato { get; set; }
        [Display(Name = "Área de interes")]
        public long AreaInteres { get; set; }
        [Display(Name = "Categoría/Área")]
        public string CategoriaDescripcion { get; set; } = null!;
        [Display(Name = "Correo electrónico")]
        [Required(ErrorMessage = "Debe ingresar un correo electrónico válido")]
        [EmailAddress]
        public string CorreoUsuario { get; set; } = null!;
    }
}

FrontEnd/Controllers/CandidatoController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Helpers;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FrontEnd.Controllers
{
    public class CandidatoController : Controller
    {
        ICandidatoDAL candidatoDAL;
        // GET: CandidatoController

        private CandidatoViewModel Convertir(Candidato candidato)
        {
            return new CandidatoViewModel
            {
                NombreCandidato = candidato.NombreCandidato,
                ApellidoCandidato = candidato.ApellidoCandidato,
                ExpCandidato = candidato.ExpCandidato,
                GradoEstudio = candidato.GradoEstudio,
                TelefonoCandidato = candidato.TelefonoCandidato,
                AreaInteres = candidato.AreaInteres,
                CorreoUsuario = candidato.CorreoUsuario,
                CategoriaDescripcion = candidato.CategoriaDescripcion
            };
        }
        public ActionResult listaCandidatosAPI()
        {
            try
            {
                ServiceRepository serviceObj = new ServiceRepository();
                HttpResponseMessage response = serviceObj.GetResponse("api/candidato/");
                response.EnsureSuccessStatusCode();
                var content = response.Content.ReadAsStringAsync().Result;
                List<Models.CandidatoViewModel> candidatos = JsonConvert.DeserializeObject<List<Models.CandidatoViewModel>>(content);

                ViewBag.Title = "All Categories";
                return View(candidatos);
            }
            catch (Exception)
            {
                throw;
            }


            //List<Candidato> candidatos;
            //CandidatoDALImpl candidatoDAL = new CandidatoDALImpl();
            //candidatos = candidatoDAL.GetAll().ToList();

            //return View(candidatos);
        }

        // GET: CandidatoController/Details/5
        public IActionResult Details(string correo)
        {
            CandidatoDALImpl candidatoDAL = new CandidatoDALImpl();
            List<Candidato> candidato = candidatoDAL.consultarCandidato(correo);
            return View(Convertir(candidato[0]));
        }

        // GET: CandidatoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CandidatoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CandidatoController/Edit/5
        public ActionResult Edit(string correo)
        {
            ViewBag.Grado = new List<string>() { "Noveno Año", "Bachiller Colegial", "Técnico Medio", "Bachiller Universitario", "Licenciado", "Maestria" };
            CandidatoDALImpl candidatoDAL = new CandidatoDALImpl();
            List<Candidato> candidato = candidatoDAL.consultarCandidato(correo);
            return View(candidato[0]);
        }

        // POST: CandidatoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Candidato candidato)
        {
            candidatoDAL = new CandidatoDALImpl();

            candidatoDAL.Update(candidato);
            return RedirectToAction("Index", "Home");
        }

        // GET: CandidatoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CandidatoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FrontEnd/Views/Candidato/Details.cshtml
@model FrontEnd.Models.CandidatoViewModel

<div class="col-6 grid-margin stretch-card" style="margin-left: auto;margin-right: auto;">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Información del candidato</h4>
            <form class="forms-sample" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NombreCandidato" class="control-label"></label>
                    <input asp-for="NombreCandidato" class="form-control" readonly/>
                    <span asp-validation-for="NombreCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ApellidoCandidato" class="control-label"></label>
                    <input asp-for="ApellidoCandidato" class="form-control" readonly/>
                    <span asp-validation-for="ApellidoCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExpCandidato" class="control-label"></label>
                    <input asp-for="ExpCandidato" type="text" class="form-control"  readonly/>
                    <span asp-validation-for="ExpCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GradoEstudio" class="control-label"></label>
                    <input asp-for="GradoEstudio" class="form-control" readonly/>
                    <span asp-validation-for="GradoEstudio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TelefonoCandidato" class="control-label"></label>
                    <input asp-for="TelefonoCandidato" class="form-control" readonly/>
                    <span asp-validation-for="TelefonoCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoriaDescripcion" class="control-label"></label>
                    <input asp-for="CategoriaDescripcion" class="form-control" readonly/>
                    <span asp-validation-for="CategoriaDescripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CorreoUsuario" class="control-label"></label>
                    <input asp-for="CorreoUsuario" class="form-control" readonly/>
                    <span asp-validation-for="CorreoUsuario" class="text-danger"></span>
                </div>
            </form>
        </div>
    </div>
</div>

FrontEnd/Views/Candidato/Edit.cshtml
@model BackEnd.Entities.Candidato

@{
    ViewData["Title"] = "Edit";
}

<div class="col-6 grid-margin stretch-card" style="margin-left: auto;margin-right: auto;">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Información personal</h4>
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CorreoUsuario" class="control-label"></label>
                    <input asp-for="CorreoUsuario" class="form-control" readonly/>
                    <span asp-validation-for="CorreoUsuario" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NombreCandidato" class="control-label"></label>
                    <input asp-for="NombreCandidato" class="form-control" />
                    <span asp-validation-for="NombreCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ApellidoCandidato" class="control-label"></label>
                    <input asp-for="ApellidoCandidato" class="form-control" />
                    <span asp-validation-for="ApellidoCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExpCandidato" class="control-label"></label>
                    <input asp-for="ExpCandidato" class="form-control" />
                    <span asp-validation-for="ExpCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TelefonoCandidato" class="control-label"></label>
                    <input asp-for="TelefonoCandidato" class="form-control" />
                    <span asp-validation-for="TelefonoCandidato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GradoEstudio" class="control-label"></label>
                    <select class = "js-example-basic-single w-100" asp-for="GradoEstudio" class="form-control" asp-items="new SelectList(ViewBag.Grado)"></select>
                    <span asp-validation-for="GradoEstudio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AreaInteres" class="control-label"></label>
                    <input asp-for="AreaInteres" class="form-control" />
                    <span asp-validation-for="AreaInteres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </form>
       </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrontEnd/Views/Candidato/Index.cshtml
@model IEnumerable<BackEnd.Entities.Candidato>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Candidatos</h1>

<h4>
    <a asp-action="Create">Registrar candidato</a>
</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GradoEstudio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelefonoCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AreaInteres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoUsuario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GradoEstudio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelefonoCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AreaInteres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoUsuario)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new {  id=item.CorreoUsuario  }) |
                @Html.ActionLink("Eliminar", "Delete", new { id=item.CorreoUsuario })
            </td>
        </tr>
}
    </tbody>
</table>

FrontEnd/Views/Candidato/listaCandidatos.cshtml
@model IEnumerable<BackEnd.Entities.Candidato>

@{
    ViewData["Title"] = "listaCandidatos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>listaCandidatos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GradoEstudio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelefonoCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AreaInteres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoUsuario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GradoEstudio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelefonoCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AreaInteres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoUsuario)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

FrontEnd/Views/Candidato/listaCandidatosAPI.cshtml
@model IEnumerable<FrontEnd.Models.CandidatoViewModel>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Candidatos</h4>
            <div class="table-responsive">
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpCandidato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GradoEstudio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriaDescripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoCandidato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpCandidato) años
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GradoEstudio) 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoriaDescripcion)
            </td>
            <td>
                @Html.HiddenFor(modelItem=>item.CorreoUsuario)
                <input type="button" value="Contacto" class="btn btn-primary" 
                                           onclick="location.href='@Url.Action("Details", "Candidato", new { correo = item.CorreoUsuario})'">
            </td>
        </tr>
}
    </tbody>
</table>

  </div>
        </div>
    </div>
</div>