FrontEnd/Controllers/EmpleoController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Helpers;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class EmpleoController : Controller
    {
        IEmpleoDAL empleoDAL;
        ICategoriaDAL categoriaDAL;
        private EmpleoViewModel Convertir(Empleo empleo)
        {
            return new EmpleoViewModel
            {
                IdEmpleo = empleo.IdEmpleo,
                IdCategoria = empleo.IdCategoria,
                CorreoReclutador = empleo.CorreoReclutador,
                EmpleoNombre = empleo.EmpleoNombre,
                ExpMinima = empleo.ExpMinima,
                GradoEstudio = empleo.GradoEstudio,
                Compania = empleo.Compania,
                EstadoPuesto = empleo.EstadoPuesto,
                Descripcion = empleo.Descripcion,
                Requisitos = empleo.Requisitos,
                CategoriaDescripcion = empleo.CategoriaDescripcion
            };
        }

        public IActionResult Index()
        {

            List<Empleo> lista;
            EmpleoDALImpl empleoDAL = new EmpleoDALImpl();
            lista = empleoDAL.LlenarEmpleos().ToList();

            List<EmpleoViewModel> empleos = new List<EmpleoViewModel>();

            foreach (Empleo item in lista)
            {
                empleos.Add(Convertir(item));
            }

            return View(empleos);
        }

        public IActionResult Create()
        {
            ViewBag.Grado = new List<string>() { "Noveno Año", "Bachiller Colegial", "Técnico Medio", "Bachiller Universitario", "Licenciado", "Maestria" };

            EmpleoViewModel empleo = new EmpleoViewModel();
            categoriaDAL = new CategoriaDALImpl();
            empleo.Categorias = categoriaDAL.GetAll();

            return View(empleo);
        }


        [HttpPost]
        public IActionResult Create(Empleo empleo)
        {
            ViewBag.Grado = new List<string>() { "Noveno Año", "Bachiller Colegial", "Técnico Medio", "Bachiller Universitario", "Licenciado", "Maestria" };

            IReclutadorDAL reclutador = new ReclutadorDALImpl();


            empleo.CorreoReclutador = HttpContext.Session.GetString("CORREO");
            empleo.Compania = reclutador.Get(empleo.CorreoReclutador).Compania;
            empleo.EstadoPuesto = "Activo";

            empleoDAL = new EmpleoDALImpl();
            empleoDAL.Add(empleo);

            return RedirectToAction("EmpleosPublicados");
        }

        [HttpPost]
        public IActionResult CrearSolicitud(EmpleoViewModel empleo)
        {
            BackEndAPI.Models.SolicitudModel solicitud = new BackEndAPI.Models.SolicitudModel();
            solicitud.IdEmpleo = empleo.IdEmpleo;
            solicitud.CorreoCandidato = HttpContext.Session.GetString("CORREO");

            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.PostResponse("api/solicitud", solicitud);
            response.EnsureSuccessStatusCode();

            return RedirectToAction("misSolicitudes","Solicitud");
          
        }


        public IActionResult Details(long id)
        {
            EmpleoDALImpl empleoDAL = new EmpleoDALImpl();

            if (empleoDAL.EmpleoAplicado(HttpContext.Session.GetString("CORREO"),id))
            {
                HttpContext.Session.SetString("APLICADO", "1");
            }
            else
            {
                HttpContext.Session.SetString("APLICADO", "0");
            }

            List<Empleo> Empleo = empleoDAL.consultarEmpleo(id);
            return View(Convertir(Empleo[0]));
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Grado = new List<string>() { "Noveno Año", "Bachiller Colegial", "Técnico Medio", "Bachiller Universitario", "Licenciado", "Maestria" };
            ViewBag.Estado = new List<string>() { "Activo","Inactivo" };

            EmpleoDALImpl empleoDAL = new EmpleoDALImpl();
            
            List<Empleo> result = empleoDAL.consultarEmpleo(id);
            EmpleoViewModel empleo = new EmpleoViewModel();
            empleo=Convertir(result[0]);
            categoriaDAL = new CategoriaDALImpl();
            empleo.Categorias = categoriaDAL.GetAll();
            return View(empleo);
        }
        [HttpPost]
        public IActionResult Edit(Empleo Empleo)
        {
            empleoDAL = new EmpleoDALImpl();

            empleoDAL.Update(Empleo);
            return RedirectToAction("EmpleosPublicados");
        }

        public IActionResult Delete(int id)
        {
            empleoDAL = new EmpleoDALImpl();
            Empleo Empleo = empleoDAL.Get(id);
            return View(Empleo);
        }
        [HttpPost]
        public IActionResult Delete(Empleo Empleo)
        {
            empleoDAL = new EmpleoDALImpl();

            empleoDAL.Remove(Empleo);
            return RedirectToAction("Index");
        }

        public IActionResult EmpleoInteligente()
        {
            CandidatoDALImpl candidato = new CandidatoDALImpl();

            List<Candidato> result = candidato.consultarCandidato(HttpContext.Session.GetString("CORREO"));
            
            EmpleoDALImpl empleoDAL = new EmpleoDALImpl();
            List<Empleo> lista = empleoDAL.EmpleoInteligente(result[0].AreaInteres,result[0].ExpCandidato,result[0].GradoEstudio).ToList();

            List<EmpleoViewModel> empleos = new List<EmpleoViewModel>();

            foreach (Empleo item in lista)
            {
                empleos.Add(Convertir(item));
            }

            return View("Index", empleos);
        }

        public IActionResult EmpleosPublicados()
        {            
            EmpleoDALImpl empleoDAL = new EmpleoDALImpl();
            List<Empleo> lista = empleoDAL.EmpleosPublicados(HttpContext.Session.GetString("CORREO")).ToList();

            List<EmpleoViewModel> empleos = new List<EmpleoViewModel>();

            foreach (Empleo item in lista)
            {
                empleos.Add(Convertir(item));
            }

            return View("Index", empleos);
        }
    }


}

FrontEnd/Controllers/HomeController.cs
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontEnd/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    @using Microsoft.AspNetCore.Http;
    @inject IHttpContextAccessor HttpContextAccessor

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

 
  
</head>
<body>
    <header id="mainheader">
        <div class="container">
            <div class="mainheader-row">
                <div class="mainheader-row-text">
                    <br />
                    <br />
                    <h1 class="display-5">Con nosotros encontrarás tu<br></h1>
                    <h1 class="display-5" style="font-weight: bold; color: #3498DB "> Trabajo Soñado</h1>
                    <h5>¡Explorá todas las diferentes opciones laborales para vos!</h5>
                   
            
                </div>

            </div>
        </div>

    </header>
    <div class="contenedor">
        <div class="cards">
            <figure>
                <img src="~/images/mac.jpg" />
            </figure>
            <div class="contenido">
                <h3>McDonald´s</h3>
                <p>
                    ¡Encontrá diferentes ofertas de empleo en
                    servicio al cliente de las empresas más grandes!
                </p>
                <a href="@Url.Action("Index","Empleo")">Conocer más</a>
            </div>
        </div>
        <div class="cards">
            <figure>
                <img src="~/images/amazon.jpg" />
            </figure>
            <div class="contenido">
                <h3>Amazon</h3>
                <p>
                    ¡Encontrá diferentes ofertas de empleo en
                    servicio al cliente de las empresas más grandes!
                </p>
                <a href="@Url.Action("Index","Empleo")">Conocer más</a>
            </div>
        </div>
        <div class="cards">
            <figure>
                <img src="~/images/unilever.jpg" />
            </figure>
            <div class="contenido">
                <h3>Unilever</h3>
                <p>
                    ¡Encontrá diferentes ofertas de empleo en
                    servicio al cliente de las empresas más grandes!
                </p>
                <a href="@Url.Action("Index","Empleo")">Conocer más</a>
            </div>
        </div>        
    </div>
    <div class="contenedor">
        <div class="cards">
            <figure>
                <img src="~/images/IBM.jpg" />
            </figure>
            <div class="contenido">
                <h3>IBM</h3>
                <p>
                    ¡Encontrá diferentes ofertas de empleo en
                    informática de las empresas más grandes!
                </p>
                <a href="@Url.Action("Index","Empleo")">Conocer más</a>
            </div>
        </div>
        <div class="cards">
            <figure>
                <img src="~/images/intel.jpg" />
            </figure>
            <div class="contenido">
                <h3>Intel</h3>
                <p>
                    ¡Encontrá diferentes ofertas de empleo en
                    informática de las empresas más grandes!
                </p>
                <a href="@Url.Action("Index","Empleo")">Conocer más</a>
            </div>
        </div>
        <div class="cards">
            <figure>
                <img src="~/images/sykes.png" />
            </figure>
            <div class="contenido">
                <h3>Sykes</h3>
                <p>
                    ¡Encontrá diferentes ofertas de empleo en
                    servicio al cliente de las empresas más grandes!
                </p>
                <a href="@Url.Action("Index","Empleo")">Conocer más</a>
            </div>
        </div>
    </div>
</body>
</html>

<style>
   .contenedor {
    width: 100%;
    display: flex;
    max-width: 1100px;
}

.cards {
    width: 100%;
    margin: 20px;
    border-radius: 6px;
    overflow: hidden;
    background: #fff;
    box-shadow: 0px 1px 10px rgba(0,0,0,0.2);
    cursor: default;
    transition: all 400ms ease;
}

.cards:hover {
        box-shadow: 5px 5px 20px rgba(0,0,0,0.4);
        transform: translateY(-3%)
}

.cards img{
    width: 100%;
    height: 310px;
}

.cards .contenido{
    padding: 15px;
    text-align: center;
}

.cards .contenido p{
    line-height: 1.5;
    color: #6a6a6a;
}

.cards .contenido h3{
    font-weight: 400;
    margin-bottom: 15px;
}

.cards .contenido a{
    text-decoration: none;
    display: inline-block;
    padding: 10px;
    margin-top: 10px;
    color: darkblue;
    border: 1px solid darkblue;
    border-radius: 4px;
    transition: all 400ms ease;
}

.cards .contenido a:hover{
    background: darkblue;
    color: #fff;
}


</style>